global.document = { addEventListener: function(){}, querySelectorAll: function(){return [];}, createElement: function(){return {};}, body: { appendChild: function(){} } };
global.window = { addEventListener: function(){} };
global.navigator = { platform: '', geolocation: null };
var PassifloraConfig = { os_name: 'WWW', menus: [] };
var PassifloraIO;
eval(require('fs').readFileSync('bin/WWW/passiflora/PassifloraIO.js','utf8'));
var src = PassifloraIO.menusavas.toString();
console.log('polyfill active:', src.indexOf('showSaveFilePicker') >= 0);
console.log('native menusavas gone:', src.indexOf('getHomeFolder') < 0);
console.log('menuopen polyfill:', PassifloraIO.menuopen.toString().indexOf('input.type') >= 0);
