#!/bin/sh
# mkmenu.sh — Generate menu.c from a menu template file.
#
# Usage: ./mkmenu.sh <template> <progname> [output]
#
# Template format:
#   - Indentation (tabs or groups of 4 spaces) sets the nesting level
#   - Level 0 entries become top-level menu bar items
#   - Level 1+ entries become items within that menu
#   - "-" alone means a separator
#   - Blank lines are skipped
#   - {{progname}} is replaced with the progname argument
#
set -e

TEMPLATE="$1"
PROGNAME="${2:-passiflora}"
OUTPUT="${3:-menu.c}"

if [ -z "$TEMPLATE" ] || [ ! -f "$TEMPLATE" ]; then
    echo "Usage: $0 <template> [progname] [output]" >&2
    echo "Error: template file '${TEMPLATE}' not found" >&2
    exit 1
fi

{
    cat <<'HEADER'
/* Generated by mkmenu.sh — do not edit */
HEADER

    printf '#define MENU_PROGNAME "%s"\n\n' "$PROGNAME"

    cat <<'TYPES'
typedef struct {
    int level;
    const char *text;
} menu_entry_t;

static const menu_entry_t menu_template[] = {
TYPES

    # Use awk to parse each line: count indentation, replace {{progname}}
    awk -v progname="$PROGNAME" '
    {
        line = $0
        level = 0

        # Count leading tabs
        while (length(line) > 0 && substr(line, 1, 1) == "\t") {
            level++
            line = substr(line, 2)
        }

        # If no tabs found, count groups of 4 leading spaces
        if (level == 0) {
            while (length(line) >= 4 && substr(line, 1, 4) == "    ") {
                level++
                line = substr(line, 5)
            }
        }

        # Strip remaining leading/trailing whitespace
        gsub(/^[ \t]+/, "", line)
        gsub(/[ \t]+$/, "", line)

        # Skip blank lines
        if (line == "") next

        # Replace {{progname}} with the actual program name
        while ((idx = index(line, "{{progname}}")) > 0) {
            line = substr(line, 1, idx - 1) progname substr(line, idx + 12)
        }

        # Escape double quotes for C string
        gsub(/"/, "\\\"", line)

        printf "    {%d, \"%s\"},\n", level, line
    }
    ' "$TEMPLATE"

    cat <<'FOOTER'
    {-1, NULL}
};
FOOTER

} > "$OUTPUT"

echo "mkmenu: $OUTPUT generated from $TEMPLATE (progname=$PROGNAME)"
