@echo off
REM mkzipfile.bat — Generate zipdata.c from a directory of files.
REM
REM Usage:  mkzipfile.bat <directory> [output]
REM
REM Zips all files in <directory> (without path prefix) and writes
REM a C source file containing the zip data as a static array.
REM Requires: PowerShell 5+, certutil (built-in)
REM
setlocal enabledelayedexpansion

set SRCDIR=%~1
set OUTPUT=%~2
if "%OUTPUT%"=="" set OUTPUT=zipdata.c

if "%SRCDIR%"=="" (
    echo Usage: %~nx0 ^<directory^> [output_file] >&2
    exit /b 1
)
if not exist "%SRCDIR%\" (
    echo Error: '%SRCDIR%' is not a directory >&2
    exit /b 1
)

REM Create a temp zip file using PowerShell
set TMPZIP=%TEMP%\mkzipfile_%RANDOM%.zip
if exist "%TMPZIP%" del /q "%TMPZIP%"

REM Compress-Archive from the source directory
powershell -NoProfile -Command ^
    "$src = (Resolve-Path '%SRCDIR%').Path; " ^
    "$dst = '%TMPZIP%'; " ^
    "Compress-Archive -Path \"$src\*\" -DestinationPath $dst -Force"

if not exist "%TMPZIP%" (
    echo Error: failed to create zip archive >&2
    exit /b 1
)

REM Generate hex using certutil, then reformat to C array
(
    echo /* Generated by mkzipfile.bat — do not edit */
    echo static const unsigned char zipdata[] = {
) > "%OUTPUT%"

REM Use certutil to hex-dump, then PowerShell to reformat as C hex bytes
powershell -NoProfile -Command ^
    "$bytes = [System.IO.File]::ReadAllBytes('%TMPZIP%'); " ^
    "$sb = [System.Text.StringBuilder]::new(); " ^
    "for ($i = 0; $i -lt $bytes.Length; $i++) { " ^
    "  if ($i -gt 0) { $sb.Append(',') | Out-Null } " ^
    "  if ($i %% 12 -eq 0) { " ^
    "    if ($i -gt 0) { $sb.AppendLine() | Out-Null } " ^
    "    $sb.Append('    ') | Out-Null " ^
    "  } " ^
    "  $sb.AppendFormat(' 0x{0:x2}', $bytes[$i]) | Out-Null " ^
    "} " ^
    "$sb.ToString()" >> "%OUTPUT%"

(
    echo.
    echo };
    echo static const size_t zipdata_len = sizeof(zipdata^);
) >> "%OUTPUT%"

REM Get file size for reporting
for %%F in ("%TMPZIP%") do set ZIPSIZE=%%~zF
del /q "%TMPZIP%"

echo mkzipfile: %OUTPUT% generated (%ZIPSIZE% bytes of ZIP data)
endlocal
exit /b 0
