#!/bin/sh
# mkmenu.sh — Generate menu.h from a menu template file.
#
# Usage: mkmenu.sh <template> <progname> [output]
#
# Template format:
#   - Indentation (tabs or groups of 4 spaces) sets the nesting level
#   - Level 0 entries become top-level menu bar items
#   - Level 1+ entries become items within that menu
#   - "-" alone means a separator
#   - Blank lines are skipped
#   - Items starting with * are native-only (kept in the C header)
#   - {{progname}} is replaced with the progname argument
#
# Output: a C header defining menu_entry_t and menu_template[].
#
set -e

TEMPLATE="$1"
PROGNAME="${2:-passiflora}"
OUTPUT="${3:-src/C/generated/menu.h}"

if [ -z "$TEMPLATE" ] || [ ! -f "$TEMPLATE" ]; then
    echo "Usage: $0 <template> <progname> [output]" >&2
    echo "Error: template file '${TEMPLATE}' not found" >&2
    exit 1
fi

# Ensure output directory exists
mkdir -p "$(dirname "$OUTPUT")"

awk -v progname="$PROGNAME" '
{
    line = $0
    level = 0

    # Count leading tabs
    while (length(line) > 0 && substr(line, 1, 1) == "\t") {
        level++
        line = substr(line, 2)
    }

    # If no tabs found, count groups of 4 leading spaces
    if (level == 0) {
        while (length(line) >= 4 && substr(line, 1, 4) == "    ") {
            level++
            line = substr(line, 5)
        }
    }

    # Strip remaining leading/trailing whitespace
    gsub(/^[ \t]+/, "", line)
    gsub(/[ \t]+$/, "", line)

    # Skip blank lines
    if (line == "") next

    # Replace {{progname}} with the actual program name
    while ((idx = index(line, "{{progname}}")) > 0) {
        line = substr(line, 1, idx - 1) progname substr(line, idx + 12)
    }

    # Items starting with * are native-only; strip the marker for the C header
    if (substr(line, 1, 1) == "*") {
        line = substr(line, 2)
        gsub(/^[ \t]+/, "", line)
    }

    # Escape backslashes and double quotes for C strings
    gsub(/\\/, "\\\\", line)
    gsub(/"/, "\\\"", line)

    levels[NR] = level
    texts[NR]  = line
    count = NR
}
END {
    printf "/* Generated by mkmenu \xe2\x80\x94 do not edit */\n"
    printf "#define MENU_PROGNAME \"%s\"\n\n", progname
    printf "typedef struct {\n"
    printf "    int level;\n"
    printf "    const char *text;\n"
    printf "} menu_entry_t;\n\n"
    printf "static const menu_entry_t menu_template[] = {\n"

    for (i = 1; i <= count; i++) {
        if (!(i in levels)) continue
        printf "    {%d, \"%s\"},\n", levels[i], texts[i]
    }

    printf "    {-1, NULL}\n"
    printf "};\n"
}
' "$TEMPLATE" > "$OUTPUT"

echo "mkmenu: $OUTPUT generated from $TEMPLATE (progname=$PROGNAME)"
