#!/bin/sh
#
# mkvfspreload.sh — Generate vfspreload.js from the contents of src/vfs/.
#
# Usage:  ./mkvfspreload.sh <vfs_dir> [output]
#
# Recursively walks <vfs_dir>, base64-encodes each file, and emits a
# JavaScript file defining _PASSIFLORA_VFS_PRELOAD — an array of
# { path: "/...", data: "base64..." } objects that the VFS IIFE uses
# to seed the virtual file system on first launch.
#
# If <vfs_dir> is empty or missing, an empty array is written.
#
set -e

VFSDIR="$1"
OUTPUT="${2:-src/www/generated/vfspreload.js}"

# Ensure output directory exists
mkdir -p "$(dirname "$OUTPUT")"

{
    echo "/* Generated by mkvfspreload.sh — do not edit */"
    echo "var _PASSIFLORA_VFS_PRELOAD = ["

    if [ -d "$VFSDIR" ]; then
        FIRST=true
        # Find every non-hidden file under VFSDIR
        find "$VFSDIR" -type f ! -name '.*' | sort | while IFS= read -r FILE; do
            # Compute the VFS path: strip VFSDIR prefix, ensure leading /
            REL="${FILE#"$VFSDIR"}"
            # Ensure starts with /
            case "$REL" in
                /*) ;;
                *)  REL="/$REL" ;;
            esac

            B64=$(base64 < "$FILE" | tr -d '\n')

            if [ "$FIRST" = true ]; then
                FIRST=false
            else
                printf ',\n'
            fi
            printf '  { path: %s, data: "%s" }' "$(printf '%s' "$REL" | sed 's/"/\\"/g; s/.*/\"&\"/')" "$B64"
        done
    fi

    echo ""
    echo "];"
} > "$OUTPUT"

# Count entries
COUNT=$(grep -c 'path:' "$OUTPUT" 2>/dev/null || echo 0)
echo "mkvfspreload: $OUTPUT generated ($COUNT file(s))"
