#!/bin/sh
#
# mkzipfile.sh — Embed a directory of files as a ZIP for the native server.
#
# Usage:  ./mkzipfile.sh <directory> [output]
#
# Zips all files in <directory> (without any path prefix) and writes:
#   archive.zip  — the raw ZIP bytes
#   zipdata.S    — assembler stub that .incbin's the ZIP (no C hex array)
#   zipdata.h    — extern declarations for zipdata / zipdata_end / zipdata_len
#
# [output] may be a directory, or a file path whose directory is used
# (historically zipdata.h). Default: current directory.
#
set -e

if [ $# -lt 1 ]; then
    echo "Usage: $0 <directory> [output_file_or_dir]" >&2
    exit 1
fi

SRCDIR="$1"
OUTPUT="${2:-.}"

if [ ! -d "$SRCDIR" ]; then
    echo "Error: '$SRCDIR' is not a directory" >&2
    exit 1
fi

if [ -d "$OUTPUT" ]; then
    OUTDIR="$OUTPUT"
else
    OUTDIR=$(dirname "$OUTPUT")
fi
mkdir -p "$OUTDIR"
OUTDIR=$(CDPATH= cd -- "$OUTDIR" && pwd)

ARCHIVE="$OUTDIR/archive.zip"
HEADER="$OUTDIR/zipdata.h"
ASMFILE="$OUTDIR/zipdata.S"

# Create a unique temp directory and place the zip archive inside it.
TMPDIR_MZ=$(mktemp -d /tmp/mkzipfile.XXXXXX)
TMPZIP="$TMPDIR_MZ/archive.zip"
trap 'rm -rf "$TMPDIR_MZ"' EXIT

# Zip all non-hidden files from inside the directory (no path prefix).
(cd "$SRCDIR" && find . -type f ! -name '.*' -print | sed 's|^\./||' | zip -@ "$TMPZIP") > /dev/null

cp "$TMPZIP" "$ARCHIVE"

# Tiny C header — the ZIP itself is never parsed as C source.
cat > "$HEADER" << 'EOF'
/* Generated by mkzipfile.sh — do not edit */
#ifndef PASSIFLORA_ZIPDATA_H
#define PASSIFLORA_ZIPDATA_H

#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char zipdata[];
extern const unsigned char zipdata_end[];

#define zipdata_len ((size_t)(zipdata_end - zipdata))

#ifdef __cplusplus
}
#endif

#endif
EOF

# Assembler stub. .incbin is handled by the assembler, so Clang's C
# frontend never sees the archive bytes (which is what overflowed it
# when the ZIP was dumped as a hex array in a header).
cat > "$ASMFILE" << EOF
/* Generated by mkzipfile.sh — do not edit */
#if defined(__APPLE__)
	.const_data
	.globl _zipdata
	.p2align 4
_zipdata:
	.incbin "$ARCHIVE"
	.globl _zipdata_end
_zipdata_end:
#elif defined(_WIN32) || defined(__CYGWIN__) || defined(__MINGW32__)
	.section .rdata,"dr"
	.globl zipdata
	.align 16
zipdata:
	.incbin "$ARCHIVE"
	.globl zipdata_end
zipdata_end:
#else
	.section .rodata,"a"
	.globl zipdata
	.align 16
zipdata:
	.incbin "$ARCHIVE"
	.globl zipdata_end
zipdata_end:
#endif
EOF

echo "mkzipfile: $ARCHIVE generated ($(wc -c < "$TMPZIP" | tr -d ' ') bytes of ZIP data)"
