#!/bin/sh
#
# mkzipfile.sh — Generate zipdata.h from a directory of files.
#
# Usage:  ./mkzipfile.sh <directory> [output]
#
# Zips all files in <directory> (without any path prefix) and writes
# a C source file containing the zip data as a static array.
# Default output is zipfile.c in the current directory.
#
set -e

if [ $# -lt 1 ]; then
    echo "Usage: $0 <directory> [output_file]" >&2
    exit 1
fi

SRCDIR="$1"
OUTPUT="${2:-zipfile.c}"

if [ ! -d "$SRCDIR" ]; then
    echo "Error: '$SRCDIR' is not a directory" >&2
    exit 1
fi

# Create a unique temp path for the zip archive.
TMPZIP=$(mktemp /tmp/mkzipfile.XXXXXX)
rm -f "$TMPZIP"              # zip needs to create the file itself
TMPZIP="$TMPZIP.zip"
trap 'rm -f "$TMPZIP"' EXIT

# Zip all non-hidden files from inside the directory (no path prefix).
(cd "$SRCDIR" && find . -type f ! -name '.*' -print | sed 's|^\./||' | zip -@ "$TMPZIP") > /dev/null

# Generate the C source file
{
    echo "/* Generated by mkzipfile.sh — do not edit */"
    echo "static const unsigned char zipdata[] = {"

    # Use xxd to convert to hex bytes
    xxd -i < "$TMPZIP" | sed 's/^/    /'

    echo "};"
    echo "static const size_t zipdata_len = sizeof(zipdata);"
} > "$OUTPUT"

echo "mkzipfile: $OUTPUT generated ($(wc -c < "$TMPZIP" | tr -d ' ') bytes of ZIP data)"
