# mkmenu.ps1 - Generate menu.h from a menu template file.
# Called by mkmenu.bat; not intended to be run directly.
param(
    [string]$template,
    [string]$progname,
    [string]$output
)

$displayname = $progname
$cfgPath = Join-Path (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)) 'src\config'
if (Test-Path $cfgPath) {
    foreach ($cfgLine in (Get-Content $cfgPath -Encoding UTF8)) {
        if ($cfgLine -match '^DISPLAYNAME\s+(.+)$') { $displayname = $Matches[1].Trim() }
    }
}

$lines = Get-Content $template -Encoding UTF8
$sb = [System.Text.StringBuilder]::new()

[void]$sb.AppendLine('/* Generated by mkmenu - do not edit */')
[void]$sb.AppendLine('#define MENU_PROGNAME "' + $progname + '"')
[void]$sb.AppendLine('#define MENU_DISPLAYNAME "' + $displayname + '"')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('typedef struct {')
[void]$sb.AppendLine('    int level;')
[void]$sb.AppendLine('    const char *text;')
[void]$sb.AppendLine('} menu_entry_t;')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('static const menu_entry_t menu_template[] = {')

$tab = [char]9
foreach ($raw in $lines) {
    $line = $raw
    $level = 0
    while ($line.Length -gt 0 -and $line[0] -eq $tab) {
        $level++; $line = $line.Substring(1)
    }
    if ($level -eq 0) {
        while ($line.Length -ge 4 -and $line.Substring(0,4) -eq '    ') {
            $level++; $line = $line.Substring(4)
        }
    }
    $line = $line.Trim()
    if ($line -eq '') { continue }
    $line = $line.Replace('{{progname}}', $progname)
    $line = $line.Replace('{{displayname}}', $displayname)
    $line = $line.Replace('"', '\"')
    [void]$sb.AppendLine('    {' + $level + ', "' + $line + '"},')
}

[void]$sb.AppendLine('    {-1, NULL}')
[void]$sb.AppendLine('};')

[System.IO.File]::WriteAllText(
    $output,
    $sb.ToString(),
    [System.Text.UTF8Encoding]::new($false)
)
