@echo off
REM mkvfspreload.bat — Generate vfspreload.js from the contents of src\vfs\.
REM
REM Usage:  mkvfspreload.bat <vfs_dir> [output]
REM
REM Recursively walks <vfs_dir>, base64-encodes each file, and emits a
REM JavaScript file defining _PASSIFLORA_VFS_PRELOAD.
REM
REM If <vfs_dir> is empty or missing, an empty array is written.
REM Requires: PowerShell 5+
REM
setlocal enabledelayedexpansion

set VFSDIR=%~1
set OUTPUT=%~2
if "%OUTPUT%"=="" set OUTPUT=src\www\generated\vfspreload.js

REM Ensure output directory exists
for %%F in ("%OUTPUT%") do mkdir "%%~dpF" 2>nul

powershell -NoProfile -Command ^
    "$vfsDir = '%VFSDIR%';" ^
    "$output = '%OUTPUT%';" ^
    "$lines = @('/* Generated by mkvfspreload.bat - do not edit */', 'var _PASSIFLORA_VFS_PRELOAD = [');" ^
    "$count = 0;" ^
    "if (Test-Path $vfsDir) {" ^
    "  $files = Get-ChildItem -Path $vfsDir -Recurse -File | Where-Object { $_.Name -notlike '.*' } | Sort-Object FullName;" ^
    "  $entries = @();" ^
    "  foreach ($f in $files) {" ^
    "    $rel = $f.FullName.Substring((Resolve-Path $vfsDir).Path.Length).Replace('\', '/');" ^
    "    if (-not $rel.StartsWith('/')) { $rel = '/' + $rel };" ^
    "    $b64 = [Convert]::ToBase64String([IO.File]::ReadAllBytes($f.FullName));" ^
    "    $entries += ('  { path: \"' + $rel + '\", data: \"' + $b64 + '\" }');" ^
    "    $count++;" ^
    "  };" ^
    "  $lines += ($entries -join \",`n\");" ^
    "};" ^
    "$lines += '];';" ^
    "[IO.File]::WriteAllText($output, ($lines -join \"`n\") + \"`n\");" ^
    "Write-Host \"mkvfspreload: $output generated ($count file(s))\""

endlocal
