@echo off
REM mkzipfile.bat — Embed a directory of files as a ZIP for the native server.
REM
REM Usage:  mkzipfile.bat <directory> [output]
REM
REM Zips all files in <directory> (without path prefix) and writes:
REM   archive.zip  — the raw ZIP bytes
REM   zipdata.S    — assembler stub that .incbin's the ZIP (no C hex array)
REM   zipdata.h    — extern declarations for zipdata / zipdata_end / zipdata_len
REM
REM [output] may be a directory, or a file path whose directory is used
REM (historically zipdata.h). Default: src\C\generated
REM
REM Requires: PowerShell 5+ (see mkzipfile.ps1)
REM
setlocal enabledelayedexpansion

set SRCDIR=%~1
set OUTPUT=%~2
if "%OUTPUT%"=="" set OUTPUT=src\C\generated\zipdata.h

if "%SRCDIR%"=="" (
    echo Usage: %~nx0 ^<directory^> [output_file_or_dir] >&2
    exit /b 1
)
if not exist "%SRCDIR%\" (
    echo Error: '%SRCDIR%' is not a directory >&2
    exit /b 1
)

if exist "%OUTPUT%\" (
    set OUTDIR=%OUTPUT%
) else (
    set OUTDIR=%~dp2
    if "!OUTDIR!"=="" set OUTDIR=src\C\generated\
)
if not exist "!OUTDIR!" mkdir "!OUTDIR!"

REM Absolute output dir with forward slashes for the assembler .incbin path
for %%I in ("!OUTDIR!.") do set OUTDIR_ABS=%%~fI
set ARCHIVE=!OUTDIR_ABS!\archive.zip
set HEADER=!OUTDIR_ABS!\zipdata.h
set ASMFILE=!OUTDIR_ABS!\zipdata.S
set ARCHIVE_ASM=!ARCHIVE:\=/!

set TMPZIP=%TEMP%\mkzipfile_%RANDOM%.zip
if exist "%TMPZIP%" del /q "%TMPZIP%"

set SCRIPT=%~dp0mkzipfile.ps1
powershell -NoProfile -ExecutionPolicy Bypass -File "%SCRIPT%" -SrcDir "%SRCDIR%" -DestZip "%TMPZIP%"
if errorlevel 1 (
    echo Error: failed to create or validate zip archive >&2
    del /q "%TMPZIP%" 2>nul
    exit /b 1
)

if not exist "%TMPZIP%" (
    echo Error: failed to create zip archive >&2
    exit /b 1
)

copy /y "%TMPZIP%" "!ARCHIVE!" >nul
if errorlevel 1 (
    echo Error: failed to write !ARCHIVE! >&2
    del /q "%TMPZIP%" 2>nul
    exit /b 1
)

> "!HEADER!" (
    echo /* Generated by mkzipfile.bat — do not edit */
    echo #ifndef PASSIFLORA_ZIPDATA_H
    echo #define PASSIFLORA_ZIPDATA_H
    echo.
    echo #include ^<stddef.h^>
    echo.
    echo #ifdef __cplusplus
    echo extern "C" {
    echo #endif
    echo.
    echo extern const unsigned char zipdata[];
    echo extern const unsigned char zipdata_end[];
    echo.
    echo #define zipdata_len ((size_t^)(zipdata_end - zipdata^)^)
    echo.
    echo #ifdef __cplusplus
    echo }
    echo #endif
    echo.
    echo #endif
)

> "!ASMFILE!" (
    echo /* Generated by mkzipfile.bat — do not edit */
    echo #if defined^(__APPLE__^)
    echo 	.const_data
    echo 	.globl _zipdata
    echo 	.p2align 4
    echo _zipdata:
    echo 	.incbin "!ARCHIVE_ASM!"
    echo 	.globl _zipdata_end
    echo _zipdata_end:
    echo #elif defined^(_WIN32^) ^|^| defined^(__CYGWIN__^) ^|^| defined^(__MINGW32__^)
    echo 	.section .rdata,"dr"
    echo 	.globl zipdata
    echo 	.align 16
    echo zipdata:
    echo 	.incbin "!ARCHIVE_ASM!"
    echo 	.globl zipdata_end
    echo zipdata_end:
    echo #else
    echo 	.section .rodata,"a"
    echo 	.globl zipdata
    echo 	.align 16
    echo zipdata:
    echo 	.incbin "!ARCHIVE_ASM!"
    echo 	.globl zipdata_end
    echo zipdata_end:
    echo #endif
)

for %%F in ("%TMPZIP%") do set ZIPSIZE=%%~zF
del /q "%TMPZIP%"

echo mkzipfile: !ARCHIVE! generated (!ZIPSIZE! bytes of ZIP data)
endlocal
exit /b 0
